# Trabalho Prático Laboratorial #2

%%javascript
// Disable Autoscrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [1]:
# Import Modules
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as dt
import ipywidgets as widgets
import plotly.graph_objects as go

In [2]:
%matplotlib inline
plt.rcParams['figure.figsize'] = [20, 10]

In [3]:

data_path = "../data"
forest_path = os.path.join(data_path, "forest-area", "API_AG.LND.FRST.K2_DS2_en_csv_v2_4019655.csv")
surface_path = os.path.join(data_path, "surface-area", "API_AG.SRF.TOTL.K2_DS2_en_csv_v2_4023648.csv")
numberOfFires_path = os.path.join(data_path, "fires", "eudb-nf.csv")

header_rows =  [0, 2]

### 1. Qual variação da área florestal de cada país ao longo do tempo?

In [4]:
# Read Datasets
forest_data = pd.read_csv(forest_path, skiprows=header_rows)

# Removes row if all values are NaN
forest_data = forest_data.dropna(axis=0, how='all')

# Removes column if all values are NaN
forest_data = forest_data.dropna(axis=1, how='all')

In [5]:
forest_data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,Forest area (sq. km),AG.LND.FRST.K2,4.2,4.200,4.200,4.200,4.200,4.20,...,4.20,4.20,4.20,4.20,4.2,4.200000e+00,4.2,4.20,4.2,4.2
1,Africa Eastern and Southern,AFE,Forest area (sq. km),AG.LND.FRST.K2,4988232.4,4968316.114,4947640.628,4911134.742,4890838.856,4870542.97,...,4765400.98,4734211.36,4703021.74,4671832.12,4640642.5,4.607876e+06,4575901.2,4544314.78,4511676.2,4479395.0
2,Afghanistan,AFG,Forest area (sq. km),AG.LND.FRST.K2,12084.4,12084.400,12084.400,12084.400,12084.400,12084.40,...,12084.40,12084.40,12084.40,12084.40,12084.4,1.208440e+04,12084.4,12084.40,12084.4,12084.4
3,Africa Western and Central,AFW,Forest area (sq. km),AG.LND.FRST.K2,2060349.0,2049660.284,2038971.568,2028282.852,2017594.136,2006905.42,...,1862169.28,1854212.96,1846256.64,1838300.32,1830344.0,1.822961e+06,1815608.1,1807898.60,1800220.1,1792580.7
4,Angola,AGO,Forest area (sq. km),AG.LND.FRST.K2,792627.8,791073.630,789519.460,787965.290,786411.120,784856.95,...,716029.38,710478.76,704928.14,699377.52,693826.9,6.882762e+05,682725.7,677175.10,671624.4,666073.8

In [7]:
columns = forest_data.columns.values.astype('U')
id_columns = columns[np.invert(np.char.isdigit(columns))]
value_columns = columns[np.char.isdigit(columns)]
data = pd.melt(forest_data, id_vars=id_columns, value_vars=value_columns, var_name='Year', value_name='Forest Area')

In [8]:
data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Forest Area
0,Aruba,ABW,Forest area (sq. km),AG.LND.FRST.K2,1990,4.2
1,Africa Eastern and Southern,AFE,Forest area (sq. km),AG.LND.FRST.K2,1990,4988232.4
2,Afghanistan,AFG,Forest area (sq. km),AG.LND.FRST.K2,1990,12084.4
3,Africa Western and Central,AFW,Forest area (sq. km),AG.LND.FRST.K2,1990,2060349.0
4,Angola,AGO,Forest area (sq. km),AG.LND.FRST.K2,1990,792627.8

In [9]:
data['Year'] = data['Year'].astype('int')
data.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
Year                int64
Forest Area       float64
dtype: object

In [10]:
countries = data['Country Code'].unique()
id_countries = np.arange(len(countries))
country_code = dict(zip(countries, id_countries))
data2 = data.replace({'Country Code': country_code})
data2.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Forest Area
0,Aruba,0,Forest area (sq. km),AG.LND.FRST.K2,1990,4.2
1,Africa Eastern and Southern,1,Forest area (sq. km),AG.LND.FRST.K2,1990,4988232.4
2,Afghanistan,2,Forest area (sq. km),AG.LND.FRST.K2,1990,12084.4
3,Africa Western and Central,3,Forest area (sq. km),AG.LND.FRST.K2,1990,2060349.0
4,Angola,4,Forest area (sq. km),AG.LND.FRST.K2,1990,792627.8

In [11]:
data2.dtypes

Country Name       object
Country Code        int64
Indicator Name     object
Indicator Code     object
Year                int64
Forest Area       float64
dtype: object

In [8]:
#line plot
#plt.rcParams['figure.figsize'] = [20, 10]
#sns.lineplot(data=data, x='Year', y= 'Forest Area', hue='Country Name')
#bar plot
#ver perdas e ganhos
#top 10 bot 10
#percentagem

In [16]:
from sklearn.cluster import OPTICS


d = data2[['Country Code', 'Year', 'Forest Area']]
d = d.dropna()
d = d.to_numpy()
clustering = OPTICS().fit(d)

In [28]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.scatter3D(d[:,0], d[:,1], d[:,2], c=d[:,0], cmap='viridis', linewidth=0.5)

In [9]:

from math import sqrt
from scipy.stats import pearsonr
from sklearn.cluster import KMeans
from scipy.cluster.vq import kmeans,vq
from scipy.spatial.distance import cdist


c4= kmeans( data[['Country Name', 'Year', 'Forest Area']],4) 
c4

ValueError: object arrays are not supported

In [ ]:
#area de pais x no ano 2020 - area de pais x no ano 1990
#criar dataset com country code (sem repetidos) e variacao
#scatter plot da variacao?
#os q tem mais variaçao fazer barplot so desse pais ao longo dos anos
#fazer por percentagem é a pergunta de baixo <-----

for dataset in data:
    data.loc[data['Year'] <= '2000', 'Status'] = 0
    data.loc[data['Year'] >= '2010', 'Status'] = 1
    data.loc[data['Year'] >= '2020', 'Status'] = 2

    
 
for dataset in data:
    data.loc[data['Year'] <= '2000', 'StatusLabel'] = '<= 2000'
    data.loc[data['Year'] >= '2010', 'StatusLabel'] = '>= 2010'
    data.loc[data['Year'] >= '2020', 'StatusLabel'] = '>= 2020'

In [ ]:
data

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Forest Area,Status,StatusLabel
0,Aruba,ABW,Forest area (sq. km),AG.LND.FRST.K2,1990,4.2,0.0,<= 2000
1,Africa Eastern and Southern,AFE,Forest area (sq. km),AG.LND.FRST.K2,1990,4988232.4,0.0,<= 2000
2,Afghanistan,AFG,Forest area (sq. km),AG.LND.FRST.K2,1990,12084.4,0.0,<= 2000
3,Africa Western and Central,AFW,Forest area (sq. km),AG.LND.FRST.K2,1990,2060349.0,0.0,<= 2000
4,Angola,AGO,Forest area (sq. km),AG.LND.FRST.K2,1990,792627.8,0.0,<= 2000
...,...,...,...,...,...,...,...,...
8241,Kosovo,XKX,Forest area (sq. km),AG.LND.FRST.K2,2020,NaN,2.0,>= 2020
8242,"Yemen, Rep.",YEM,Forest area (sq. km),AG.LND.FRST.K2,2020,5490.0,2.0,>= 2020
8243,South Africa,ZAF,Forest area (sq. km),AG.LND.FRST.K2,2020,170500.9,2.0,>= 2020
8244,Zambia,ZMB,Forest area (sq. km),AG.LND.FRST.K2,2020,448140.3,2.0,>= 2020
8245,Zimbabwe,ZWE,Forest area (sq. km),AG.LND.FRST.K2,2020,174445.8,2.0,>= 2020

In [ ]:
#scatterplot
data.head()
plt.rcParams['figure.figsize'] = [20, 10]
fig=sns.scatterplot(data=data, x='Year', y= 'Forest Area', hue='Country Name')
plt.show()

In [ ]:
df1, df2 = data.loc[data['Status'] == 0 ] , data.loc[data['Status'] == 1 ]

In [ ]:
df1

In [ ]:
#barplot

data.head()
plt.rcParams['figure.figsize'] = [20, 10]
sns.barplot(x='Country Code', y= 'Forest Area', data=df1, hue='Year')

Dizer quais os 10 paises com maior perda, 10 paises com maior ganho, paises que nao alterou nada ao longo dos anos

### 2. Qual o rácio entre a área florestal e a área total de cada paí

In [4]:
# Read Datasets
forest_data = pd.read_csv(forest_path, skiprows=header_rows)
surface_data = pd.read_csv(surface_path, skiprows=header_rows)

# Removes row if all values are NaN
forest_data = forest_data.dropna(axis=0, how='all')
surface_data = surface_data.dropna(axis=0, how='all')

# Removes column if all values are NaN
forest_data = forest_data.dropna(axis=1, how='all')
surface_data = surface_data.dropna(axis=1, how='all')

In [5]:
# Visualize dataframe structure
forest_data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1990,1991,1992,1993,1994,1995,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,Forest area (sq. km),AG.LND.FRST.K2,4.2,4.200,4.200,4.200,4.200,4.20,...,4.20,4.20,4.20,4.20,4.2,4.200000e+00,4.2,4.20,4.2,4.2
1,Africa Eastern and Southern,AFE,Forest area (sq. km),AG.LND.FRST.K2,4988232.4,4968316.114,4947640.628,4911134.742,4890838.856,4870542.97,...,4765400.98,4734211.36,4703021.74,4671832.12,4640642.5,4.607876e+06,4575901.2,4544314.78,4511676.2,4479395.0
2,Afghanistan,AFG,Forest area (sq. km),AG.LND.FRST.K2,12084.4,12084.400,12084.400,12084.400,12084.400,12084.40,...,12084.40,12084.40,12084.40,12084.40,12084.4,1.208440e+04,12084.4,12084.40,12084.4,12084.4
3,Africa Western and Central,AFW,Forest area (sq. km),AG.LND.FRST.K2,2060349.0,2049660.284,2038971.568,2028282.852,2017594.136,2006905.42,...,1862169.28,1854212.96,1846256.64,1838300.32,1830344.0,1.822961e+06,1815608.1,1807898.60,1800220.1,1792580.7
4,Angola,AGO,Forest area (sq. km),AG.LND.FRST.K2,792627.8,791073.630,789519.460,787965.290,786411.120,784856.95,...,716029.38,710478.76,704928.14,699377.52,693826.9,6.882762e+05,682725.7,677175.10,671624.4,666073.8

In [6]:
# Visualize dataframe structure
surface_data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1961,1962,1963,1964,1965,1966,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,Surface area (sq. km),AG.SRF.TOTL.K2,180.0,180.0,180.0,180.0,180.0,180.0,...,1.800000e+02,1.800000e+02,180.00,1.800000e+02,1.800000e+02,1.800000e+02,1.800000e+02,1.800000e+02,180.00,1.800000e+02
1,Africa Eastern and Southern,AFE,Surface area (sq. km),AG.SRF.TOTL.K2,12718531.0,12718531.0,12718531.0,12718531.0,12718531.0,12718531.0,...,1.263289e+07,1.263290e+07,15121164.46,1.512116e+07,1.512116e+07,1.512116e+07,1.512116e+07,1.512116e+07,15121155.64,1.512116e+07
2,Afghanistan,AFG,Surface area (sq. km),AG.SRF.TOTL.K2,652860.0,652860.0,652860.0,652860.0,652860.0,652860.0,...,6.528600e+05,6.528600e+05,652860.00,6.528600e+05,6.528600e+05,6.528600e+05,6.528600e+05,6.528600e+05,652860.00,6.528600e+05
3,Africa Western and Central,AFW,Surface area (sq. km),AG.SRF.TOTL.K2,9166270.0,9166270.0,9166270.0,9166270.0,9166270.0,9166270.0,...,9.166270e+06,9.166270e+06,9166270.00,9.166270e+06,9.166270e+06,9.166270e+06,9.166270e+06,9.166270e+06,9166270.00,9.166270e+06
4,Angola,AGO,Surface area (sq. km),AG.SRF.TOTL.K2,1246700.0,1246700.0,1246700.0,1246700.0,1246700.0,1246700.0,...,1.246700e+06,1.246700e+06,1246700.00,1.246700e+06,1.246700e+06,1.246700e+06,1.246700e+06,1.246700e+06,1246700.00,1.246700e+06

In [20]:
# Descriptive Statistics
forest_data.describe()

,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
count,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,...,2.620000e+02,2.620000e+02,2.620000e+02,2.620000e+02,2.620000e+02,2.620000e+02,2.610000e+02,2.610000e+02,2.570000e+02,2.570000e+02
mean,1.716940e+06,1.714981e+06,1.711027e+06,1.706319e+06,1.702496e+06,1.698673e+06,1.694851e+06,1.691028e+06,1.687205e+06,1.683383e+06,...,1.639866e+06,1.637200e+06,1.634535e+06,1.631870e+06,1.629205e+06,1.627007e+06,1.476944e+06,1.474458e+06,1.494767e+06,1.492194e+06
std,5.161549e+06,5.154155e+06,5.142815e+06,5.130501e+06,5.119503e+06,5.108515e+06,5.097539e+06,5.086574e+06,5.075620e+06,5.064677e+06,...,4.962221e+06,4.956107e+06,4.950007e+06,4.943920e+06,4.937848e+06,4.933129e+06,4.323285e+06,4.318040e+06,4.342049e+06,4.336621e+06
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,3.239975e+03,3.376367e+03,3.436115e+03,3.504298e+03,3.542130e+03,3.579963e+03,3.604395e+03,3.600690e+03,3.596985e+03,3.593280e+03,...,3.382140e+03,3.366980e+03,3.351820e+03,3.336660e+03,3.321500e+03,3.306325e+03,3.291000e+03,3.237000e+03,3.685700e+03,3.695000e+03
50%,3.538585e+04,3.658068e+04,3.640565e+04,3.623062e+04,3.609940e+04,3.628148e+04,3.646355e+04,3.664562e+04,3.682770e+04,3.700977e+04,...,3.646397e+04,3.623324e+04,3.593452e+04,3.527616e+04,3.535905e+04,3.563085e+04,3.562600e+04,3.551000e+04,3.611090e+04,3.611090e+04
75%,2.767877e+05,2.764545e+05,2.761212e+05,2.757879e+05,2.754547e+05,2.751214e+05,2.747882e+05,2.744549e+05,2.741216e+05,2.737884e+05,...,2.728120e+05,2.726615e+05,2.725110e+05,2.723605e+05,2.722100e+05,2.722000e+05,2.493500e+05,2.493500e+05,2.798000e+05,2.798000e+05
max,4.128269e+07,4.121003e+07,4.113736e+07,4.106469e+07,4.099203e+07,4.091936e+07,4.084669e+07,4.077402e+07,4.070136e+07,4.062869e+07,...,4.012364e+07,4.009056e+07,4.005748e+07,4.002440e+07,3.999132e+07,3.995825e+07,3.066349e+07,3.061417e+07,3.056222e+07,3.051179e+07

In [21]:
# Descriptive Statistics
surface_data.describe()

,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
count,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,2.580000e+02,...,2.630000e+02,2.630000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.650000e+02,2.640000e+02
mean,5.313340e+06,5.313340e+06,5.313340e+06,5.313340e+06,5.313340e+06,5.313340e+06,5.313340e+06,5.313340e+06,5.313340e+06,5.313340e+06,...,5.211450e+06,5.211454e+06,5.317571e+06,5.318693e+06,5.324044e+06,5.324179e+06,5.324288e+06,5.324315e+06,5.324460e+06,5.344140e+06
std,1.539313e+07,1.539313e+07,1.539313e+07,1.539313e+07,1.539313e+07,1.539313e+07,1.539313e+07,1.539313e+07,1.539313e+07,1.539313e+07,...,1.526285e+07,1.526285e+07,1.549852e+07,1.550130e+07,1.551507e+07,1.551545e+07,1.551579e+07,1.551587e+07,1.551633e+07,1.554088e+07
min,2.027000e+00,2.027000e+00,2.027000e+00,2.027000e+00,2.027000e+00,2.027000e+00,2.027000e+00,2.027000e+00,2.027000e+00,2.027000e+00,...,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01,1.000000e+01
25%,2.302750e+04,2.302750e+04,2.302750e+04,2.302750e+04,2.302750e+04,2.302750e+04,2.302750e+04,2.302750e+04,2.302750e+04,2.302750e+04,...,1.942500e+04,1.942500e+04,2.027000e+04,2.027000e+04,2.067500e+04,2.067500e+04,2.067500e+04,2.067500e+04,2.048000e+04,2.090000e+04
50%,2.112850e+05,2.112850e+05,2.112850e+05,2.112850e+05,2.112850e+05,2.112850e+05,2.112850e+05,2.112850e+05,2.112850e+05,2.112850e+05,...,1.967100e+05,1.967100e+05,1.999490e+05,1.999490e+05,1.999490e+05,1.999490e+05,1.999490e+05,1.999500e+05,1.999500e+05,2.037750e+05
75%,1.261925e+06,1.261925e+06,1.261925e+06,1.261925e+06,1.261925e+06,1.261925e+06,1.261925e+06,1.261925e+06,1.261925e+06,1.261925e+06,...,1.243445e+06,1.243445e+06,1.246700e+06,1.246700e+06,1.246700e+06,1.246700e+06,1.246700e+06,1.246700e+06,1.246700e+06,1.251775e+06
max,1.316353e+08,1.316353e+08,1.316353e+08,1.316353e+08,1.316353e+08,1.316353e+08,1.316353e+08,1.316353e+08,1.316353e+08,1.316353e+08,...,1.317846e+08,1.317848e+08,1.342731e+08,1.343020e+08,1.345433e+08,1.345462e+08,1.345489e+08,1.345497e+08,1.345532e+08,1.345427e+08

In [17]:
# Displays Columns Names
forest_data.columns.values

array(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005',
       '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020'],
      dtype=object)

In [16]:
# Displays Columns Names
surface_data.columns.values

array(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976',
       '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992',
       '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018'], dtype=object)

In [9]:
# Keeps columns common to both dataframes
drop_columns = ['Indicator Name', 'Indicator Code']
surface = surface_data.drop(columns=[col for col in surface_data if (col not in forest_data.columns.values) or (col in drop_columns)])
forest = forest_data.drop(columns=[col for col in forest_data if (col not in surface_data.columns.values) or (col in drop_columns)])

In [10]:
# Calculates Ratio Pairwise
# Ver se está correcto
data = forest.combine(surface, lambda x, y: x / y if x.dtype != object and y.dtype != object else x)

In [11]:
data.head()

,Country Name,Country Code,1990,1991,1992,1993,1994,1995,1996,1997,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,0.023333,0.023333,0.023333,0.023333,0.023333,0.023333,0.023333,0.023333,...,0.023333,0.023333,0.023333,0.023333,0.023333,0.023333,0.023333,0.023333,0.023333,0.023333
1,Africa Eastern and Southern,AFE,0.392202,0.390636,0.389010,0.389744,0.388133,0.386522,0.384912,0.383301,...,0.360067,0.379691,0.315148,0.313085,0.311023,0.308960,0.306897,0.304730,0.302616,0.300527
2,Afghanistan,AFG,0.018510,0.018510,0.018510,0.018510,0.018510,0.018510,0.018510,0.018510,...,0.018510,0.018510,0.018510,0.018510,0.018510,0.018510,0.018510,0.018510,0.018510,0.018510
3,Africa Western and Central,AFW,0.224775,0.223609,0.222443,0.221277,0.220111,0.218945,0.217779,0.216612,...,0.204932,0.204023,0.203155,0.202287,0.201419,0.200551,0.199683,0.198877,0.198075,0.197234
4,Angola,AGO,0.635781,0.634534,0.633287,0.632041,0.630794,0.629548,0.628301,0.627054,...,0.583244,0.578792,0.574340,0.569888,0.565435,0.560983,0.556531,0.552078,0.547626,0.543174

In [12]:
# Unpivot dataframe from wide to long format
columns = data.columns.values.astype('U')
id_columns = columns[np.invert(np.char.isdigit(columns))]
value_columns = columns[np.char.isdigit(columns)]
data2 = pd.melt(data, id_vars=id_columns, value_vars=value_columns, var_name='Year', value_name='Ratio')

In [13]:
data2.head()

                  Country Name Country Code  Year     Ratio
0                        Aruba          ABW  1990  0.023333
1  Africa Eastern and Southern          AFE  1990  0.392202
2                  Afghanistan          AFG  1990  0.018510
3   Africa Western and Central          AFW  1990  0.224775
4                       Angola          AGO  1990  0.635781

In [14]:
# Gráfico Interactivo
countries = data2['Country Name'].unique()
checkboxes = list()
menu = list()
n_cols = 3

for country in countries:
    checkbox = widgets.Checkbox(
        value=False,
        description=country,
        disabled=False,
        indent=False
    )
    checkboxes.append(checkbox)

for col in range(n_cols):
    vertical_box = widgets.VBox([checkboxes[i] for i in range(col, len(checkboxes), n_cols)])
    menu.append(vertical_box)

ui = widgets.HBox(menu)

def select(**kwargs):
    selected = []
    for key in kwargs:
        if kwargs[key] is True:
            selected.append(key)
    sns.lineplot(data=data2[data2['Country Name'].isin(selected)], x='Year', y='Ratio', hue='Country Name')

arg_dict = {checkbox.description: checkbox for checkbox in checkboxes}
out = widgets.interactive_output(select, arg_dict)
display(ui, out)

HBox(children=(VBox(children=(Checkbox(value=False, description='Aruba', indent=False), Checkbox(value=False, …

Output()

## Clustering
#### Sobre que dados?

#### Questões:
1. Quais os países que têm maior rácio?
2. Quais os países que têm menor rácio?
3. Quais os países que apresentam maior variação no seu rácio? Porquê?

#### Algoritmos:
- K-means (Tem de ser o K-means que iterativamente vai descobrir o número de clusters dado que não possuímos o número de clusters à priori)
- OPTICS (Versão melhorada do DBSCAN)
- Outros?

In [28]:
countries = data['Country Code'].unique()
id_countries = np.arange(len(countries))
country_code = dict(zip(countries, id_countries))
data3 = data2.replace({'Country Code': country_code})
data4 = data3[data3['Year'] == '2018']
data4

                     Country Name  Country Code  Year     Ratio
7448                        Aruba             0  2018  0.023333
7449  Africa Eastern and Southern             1  2018  0.300527
7450                  Afghanistan             2  2018  0.018510
7451   Africa Western and Central             3  2018  0.197234
7452                       Angola             4  2018  0.543174
...                           ...           ...   ...       ...
7709                       Kosovo           261  2018       NaN
7710                  Yemen, Rep.           262  2018  0.010398
7711                 South Africa           263  2018  0.140456
7712                       Zambia           264  2018  0.600450
7713                     Zimbabwe           265  2018  0.448785

[266 rows x 4 columns]

In [43]:
# Gráfico Interactivo
column = 'Year'
years = data3[column].unique()

dropdown = widgets.Dropdown(
    options=years,
    value=years[0],
    description=column,
    disabled=False,
)

def update(year):
    sns.scatterplot(data=data3[data3['Year'] == year], x='Country Code', y='Ratio', hue='Country Code', palette='viridis')

out = widgets.interactive(update, year=dropdown)

display(out)

interactive(children=(Dropdown(description='Year', options=('1990', '1991', '1992', '1993', '1994', '1995', '1…

In [69]:
# Unpivot dataframe from wide to long format
columns = surface.columns.values.astype('U')
id_columns = columns[np.invert(np.char.isdigit(columns))]
value_columns = columns[np.char.isdigit(columns)]
surface2 = pd.melt(surface, id_vars=id_columns, value_vars=value_columns, var_name='Year', value_name='Surface Area')
surface2 = surface2.dropna()

In [74]:
surface2.dropna()

                     Country Name Country Code  Year  Surface Area
0                           Aruba          ABW  1990         180.0
1     Africa Eastern and Southern          AFE  1990    12718531.0
2                     Afghanistan          AFG  1990      652860.0
3      Africa Western and Central          AFW  1990     9166270.0
4                          Angola          AGO  1990     1246700.0
...                           ...          ...   ...           ...
7708                        Samoa          WSM  2018        2840.0
7710                  Yemen, Rep.          YEM  2018      527970.0
7711                 South Africa          ZAF  2018     1219090.0
7712                       Zambia          ZMB  2018      752610.0
7713                     Zimbabwe          ZWE  2018      390760.0

[7628 rows x 4 columns]

In [75]:
# Unpivot dataframe from wide to long format
columns = forest.columns.values.astype('U')
id_columns = columns[np.invert(np.char.isdigit(columns))]
value_columns = columns[np.char.isdigit(columns)]
forest2 = pd.melt(forest, id_vars=id_columns, value_vars=value_columns, var_name='Year', value_name='Forest Area')
forest2 = forest2.dropna()

In [76]:
countries = forest['Country Code'].unique()
id_countries = np.arange(len(countries))
country_code = dict(zip(countries, id_countries))
forest2.replace({'Country Code': country_code}, inplace=True)
surface2.replace({'Country Code': country_code}, inplace=True)

In [80]:
join = forest2.merge(surface2, how='inner', on=['Country Name', 'Country Code', 'Year'])
join

,Country Name,Country Code,Year,Forest Area,Surface Area
0,Aruba,0,1990,4.2,180.0
1,Africa Eastern and Southern,1,1990,4988232.4,12718531.0
2,Afghanistan,2,1990,12084.4,652860.0
3,Africa Western and Central,3,1990,2060349.0,9166270.0
4,Angola,4,1990,792627.8,1246700.0
...,...,...,...,...,...
7515,Samoa,260,2018,1626.3,2840.0
7516,"Yemen, Rep.",262,2018,5490.0,527970.0
7517,South Africa,263,2018,171228.9,1219090.0
7518,Zambia,264,2018,451904.6,752610.0
7519,Zimbabwe,265,2018,175367.2,390760.0

In [81]:
# Gráfico Interactivo
years = outer_join['Year'].unique()

dropdown = widgets.Dropdown(
    options=years,
    value=years[0],
    description='Year',
    disabled=False,
)

def update(year):
    sns.scatterplot(data=join[join['Year'] == year], x='Surface Area', y='Forest Area', hue='Country Code', palette='viridis')

out = widgets.interactive(update, year=dropdown)

display(out)

interactive(children=(Dropdown(description='Year', options=('1990', '1991', '1992', '1993', '1994', '1995', '1…

In [ ]:
# No ano de 2018
from sklearn.cluster import OPTICS


d = data2[['Country Code', 'Year', 'Forest Area']]
d = d.dropna()
d = d.to_numpy()
clustering = OPTICS().fit(d)

- #### Agrupamento / Group By por país?
- #### Procurar outro tipo de plots
- #### Que informação podemos tirar desses gráficos?

### 3. Como se comparam os vários países do mundo a nível de incêndios?

### 4. Como se compara perda de floresta ao longo dos anos em cada país com os incêndios que ocorreram em cada um desses anos?

In [ ]:
#bea
# Read Datasets
fires_data = pd.read_csv(numberOfFires_path)

# Removes row if all values are NaN
fires_data = fires_data.dropna(axis=0, how='all')

# Removes column if all values are NaN
fires_data = fires_data.dropna(axis=1, how='all')
#substituir nan por 0 para dar para fazer o plot?
fires_data = fires_data.fillna(0)

# merge do dataset incendios com area florestal (para nao contar com anos e paises q nao estejam nos 2 datasets)
# plot de media de numero de incendios por pais?
    #ver quais os paises com mais incendios, quais os commenos incendios, coincide com pergunta 1 ou 2?
# mapa correlacao
#

In [ ]:
fires_data

,Number of fires,Portugal,Spain,France,Italy,Greece,Algeria,Austria,Bulgaria,Croatia,...,Lithuania,Morocco,Norway,Poland,Romania,Slovakia,Slovenia,Sweden,Switzerland,Turkey
0,1981,6730,10878,5173,14503,1159,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,152,0.0
1,1982,3626,6545,5308,9557,1045,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,85,0.0
2,1983,4539,4791,4659,7956,968,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118,0.0
3,1984,7356,7203,5672,8482,1284,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,183,0.0
4,1985,8441,12238,6249,18664,1442,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,113,0.0
5,1986,5036,7570,4353,9398,1082,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,87.0,0.0,0.0,0.0,87,0.0
6,1987,7705,8679,3043,11972,1266,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,121,0.0
7,1988,6131,9247,2837,13588,1898,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,18.0,0.0,0.0,0.0,78,0.0
8,1989,21896,20811,6763,9669,1284,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,43.0,0.0,0.0,0.0,189,0.0
9,1990,10745,12913,5881,14477,1322,0.0,0.0,0.0,0.0,...,0.0,179.0,0.0,5756.0,131.0,0.0,0.0,0.0,252,1750.0
10,1991,14327,13531,3888,11965,858,0.0,0.0,73.0,0.0,...,0.0,247.0,0.0,3528.0,42.0,0.0,0.0,0.0,151,1481.0
11,1992,14954,15955,4002,14641,2582,0.0,0.0,602.0,325.0,...,1180.0,182.0,0.0,11858.0,187.0,0.0,0.0,0.0,84,2117.0
12,1993,16101,14254,4769,14412,2406,0.0,0.0,1196.0,372.0,...,634.0,187.0,0.0,8821.0,159.0,0.0,0.0,0.0,83,2545.0
13,1994,19983,19263,4618,11588,1763,0.0,0.0,667.0,181.0,...,715.0,417.0,0.0,10705.0,121.0,366.0,0.0,0.0,86,3239.0
14,1995,34116,25827,6563,7378,1438,0.0,0.0,114.0,109.0,...,472.0,528.0,0.0,7678.0,62.0,254.0,0.0,0.0,96,1770.0
15,1996,28626,16771,6401,9093,1508,0.0,0.0,246.0,305.0,...,894.0,220.0,0.0,7923.0,72.0,662.0,0.0,4854.0,128,1645.0
16,1997,23497,22320,8005,11612,2273,0.0,0.0,200.0,305.0,...,565.0,391.0,0.0,6817.0,37.0,535.0,0.0,7057.0,180,1339.0
17,1998,34676,22446,6289,9540,1842,0.0,0.0,578.0,441.0,...,258.0,416.0,0.0,6165.0,59.0,1056.0,0.0,2503.0,121,1932.0
18,1999,25477,18237,4960,6932,1486,0.0,0.0,320.0,223.0,...,1022.0,385.0,0.0,9820.0,138.0,426.0,0.0,4707.0,50,2075.0
19,2000,34109,24118,4603,8595,2581,0.0,0.0,1710.0,706.0,...,654.0,321.0,0.0,12426.0,688.0,824.0,0.0,4708.0,69,2353.0
20,2001,26533,19547,4309,7134,2535,0.0,0.0,825.0,299.0,...,287.0,327.0,117.0,4480.0,268.0,311.0,0.0,4831.0,67,2631.0
21,2002,26488,19929,4097,4601,1141,0.0,0.0,402.0,176.0,...,1596.0,202.0,213.0,10101.0,516.0,570.0,60.0,6490.0,118,1471.0
22,2003,26195,18616,7023,9697,1452,0.0,0.0,452.0,532.0,...,885.0,392.0,198.0,17087.0,203.0,872.0,224.0,8282.0,301,2177.0
23,2004,21870,21396,3775,6428,1748,0.0,0.0,294.0,204.0,...,468.0,714.0,119.0,7006.0,34.0,153.0,51.0,4955.0,74,1762.0
24,2005,35697,25492,4698,7951,1544,0.0,954.0,241.0,147.0,...,301.0,662.0,122.0,12049.0,64.0,287.0,73.0,4573.0,88,1530.0
25,2006,19929,16354,4615,5634,1417,0.0,912.0,393.0,181.0,...,1545.0,381.0,205.0,11541.0,105.0,237.0,112.0,4618.0,80,2227.0
26,2007,18722,10936,3367,10639,1983,0.0,750.0,1479.0,345.0,...,251.0,340.0,65.0,8302.0,478.0,463.0,140.0,3737.0,83,2829.0
27,2008,13832,11655,2809,6486,1481,0.0,0.0,582.0,275.0,...,301.0,273.0,171.0,9090.0,91.0,182.0,74.0,5420.0,56,2135.0
28,2009,26119,15643,4888,5422,1063,0.0,218.0,314.0,181.0,...,471.0,501.0,109.0,9162.0,190.0,347.0,120.0,4180.0,88,1793.0
29,2010,22026,11721,3862,4884,1052,0.0,192.0,222.0,131.0,...,104.0,629.0,62.0,4680.0,70.0,127.0,32.0,3120.0,78,1861.0
30,2011,25221,16414,4290,8181,1613,2487.0,356.0,635.0,280.0,...,142.0,606.0,49.0,8172.0,340.0,303.0,114.0,3534.0,107,1954.0
31,2012,21176,17503,3927,8252,1559,5110.0,312.0,876.0,569.0,...,81.0,484.0,24.0,9265.0,911.0,513.0,168.0,2213.0,74,2450.0
32,2013,19291,10626,2223,2936,862,2443.0,357.0,408.0,137.0,...,123.0,411.0,42.0,4883.0,116.0,233.0,75.0,4878.0,58,3755.0
33,2014,7067,9771,2778,3257,552,4629.0,369.0,151.0,43.0,...,155.0,460.0,133.0,5245.0,83.0,153.0,35.0,4374.0,59,2149.0
34,2015,15851,11928,4440,5442,510,2383.0,345.0,429.0,177.0,...,247.0,425.0,29.0,12257.0,250.0,242.0,93.0,2700.0,162,2150.0
35,2016,13261,8817,4285,4793,777,3150.0,317.0,584.0,151.0,...,98.0,422.0,345.0,5286.0,174.0,136.0,90.0,5454.0,63,3188.0

In [ ]:
#criar coluna country com os paises e coluna number of fires com o numero dos fogos
columns = fires_data.columns.values.astype('U')
id_columns = columns[0]
value_columns = columns[1:]
data = pd.melt(fires_data, id_vars=id_columns, value_vars=value_columns, var_name='Country', value_name='Number of Fires')

In [ ]:
data

     Number of fires   Country  Number of Fires
0               1981  Portugal           6730.0
1               1982  Portugal           3626.0
2               1983  Portugal           4539.0
3               1984  Portugal           7356.0
4               1985  Portugal           8441.0
..               ...       ...              ...
967             2012    Turkey           2450.0
968             2013    Turkey           3755.0
969             2014    Turkey           2149.0
970             2015    Turkey           2150.0
971             2016    Turkey           3188.0

[972 rows x 3 columns]

### 5. Como varia a área florestal ao longo dos anos com as atividades económicas (agricultura e mineração) de cada país?

In [ ]:
#bea
#variacao atividades economicas
    #paises com mais variacao, menos variacao
#comparar com conclusao da pergunta 1

### 6. Como se relacionam os diferentes tipos de floresta com a área florestal ardida?

In [ ]:
#clau

### 7. Como se relaciona a densidade populacional com a área florestal em cada país ao longo do tempo?

### 8. Como se relaciona o PIB per capita com a desflorestação em cada país ao longo do tempo?

In [ ]:
#bea
#grafico variacao do pib
# merge dos datasets e correlacao

### 9. Como se relaciona a temperatura, precipitação, humidade, vento de cada país com os incêndios ocorridos por ano?

In [ ]:
#correlacao

## Fim